import urllib.parse

# Azure Cognitive Search configuration
AZURE_SEARCH_ENDPOINT = "AZURE_COGNITIVE_SERVICE_ENDPOINT"
AZURE_SEARCH_KEY = "AZURE_COGNITIVE_SERVICE_ADMIN_KEY"
AZURE_SEARCH_INDEX_NAME = "AZURE_SEARCH_SERIVE_CLUSTER_INDEX_NAME"

# OpenAI API Key
AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY"

# MongoDB Configuration
COSMOSDB_USERNAME = "COSMOSDB_USERNAME"
COSMOSDB_PASSWORD = "COSMOSDB_PASSWORD"
MONGO_DB_HOST = "MONGO_DB_CLUSTER_HOST_LINK"

# Encode credentials for MongoDB URI
COSMOSDB_USERNAME = urllib.parse.quote_plus(COSMOSDB_USERNAME)
COSMOSDB_PASSWORD = urllib.parse.quote_plus(COSMOSDB_PASSWORD)
COSMOSDB_CONNECTION_STRING = f"mongodb+srv://{COSMOSDB_USERNAME}:{COSMOSDB_PASSWORD}@{MONGO_DB_HOST}/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
